# Generated by Django 3.2.5 on 2021-07-12 11:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('trips', '0003_trip_datetime'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('places_quantity', models.PositiveIntegerField(verbose_name='Кол-во зарезервированных мест')),
                ('datetime', models.DateTimeField(verbose_name='На какой день и время забронировано')),
                ('arrive_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arrive_from_reservations', to='trips.breakpoint', verbose_name='Откуда')),
                ('arrive_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arrive_to_reservations', to='trips.breakpoint', verbose_name='Куда')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='trips.trip', verbose_name='Поездка')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to=settings.AUTH_USER_MODEL, verbose_name='Зарезервировано пользователем')),
            ],
            options={
                'verbose_name': 'Бронь',
                'verbose_name_plural': 'Список бронирований',
            },
        ),
    ]
