# Generated by Django 3.2.5 on 2021-07-11 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='Название автомобиля')),
                ('num_places', models.PositiveIntegerField(default=4, verbose_name='Кол-во мест')),
                ('number', models.CharField(max_length=50, verbose_name='номер автомобиля')),
                ('color', models.CharField(max_length=20, verbose_name='цвет автомобиля')),
            ],
            options={
                'verbose_name': 'Машина',
                'verbose_name_plural': 'Машины',
            },
        ),
        migrations.CreateModel(
            name='CarImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.URLField()),
            ],
        ),
    ]
