# Generated by Django 3.2.5 on 2021-07-14 09:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_car_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='carimages',
            name='car',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='car_images', to='cars.car'),
        ),
    ]
