# Generated by Django 3.2.5 on 2021-07-11 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('mark_type', models.CharField(choices=[('Camera', 'Камера'), ('Cafe', 'Кафе'), ('Police', 'Полиция')], max_length=30)),
                ('num_stars', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], max_length=1, verbose_name='Оставлено звёзд')),
            ],
            options={
                'verbose_name': 'Метка',
                'verbose_name_plural': 'Метки',
            },
        ),
        migrations.CreateModel(
            name='MarkImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_url', models.URLField()),
            ],
            options={
                'verbose_name': 'Фотография места',
                'verbose_name_plural': 'Фотографии мест',
            },
        ),
    ]
