# Generated by Django 3.2.5 on 2021-07-12 11:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(1995, 1, 1, 1, 0), verbose_name='Дата и время поездки'),
        ),
    ]
