# Generated by Django 3.2.5 on 2021-07-15 09:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0003_trip_datetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='breakpoint',
            name='msg',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='breakpoint',
            name='price',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='LockedPlace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place_index', models.PositiveIntegerField()),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locked_places', to='trips.trip')),
            ],
            options={
                'verbose_name': 'Место недоступное для бронирования',
                'verbose_name_plural': 'Места недоступные для бронирования',
            },
        ),
    ]
