# Generated by Django 3.2.5 on 2021-07-15 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0004_auto_20210715_0937'),
    ]

    operations = [
        migrations.AddField(
            model_name='breakpoint',
            name='is_back_trip',
            field=models.BooleanField(default=False),
        ),
    ]
